### ISSUE TITLE
License of this extension?

### ISSUE THREAD

**Issue by jankeromnes** [Skn0tt/markdown-link-expander#2]
Hi @Skn0tt!

I was wondering, what license is your extension published under? I ask because we would like to have your extension on https://open-vsx.org, so that it can be used by non-Microsoft tools like VSCodium, Theia, Gitpod, Eclipse Che, etc.

See also https://github.com/open-vsx/publish-extensions/pull/95 (which proposes automatically publishing your extension to OpenVSX under a generic bot user -- although you could also publish it directly yourself by running just the single command `npx ovsx publish` -- please let me know if you'd prefer that).

**Comment by Skn0tt** [comment]
Hi @jankeromnes ! Sorry I forgot the license  😅 I've put it under MIT, feel free to publish it under the bot user :D

**Comment by jankeromnes** [comment]
Awesome, many thanks @Skn0tt for the quick response! This resolves my issue. 😊

**Comment by spoenemann** [comment]
@Skn0tt could you create a new version that includes the license? It is not available in 0.1.1 yet.

Also, would you like to publish the extension to Open VSX yourself? Instructions are [in the Wiki](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions).

**Comment by Skn0tt** [comment]
I published 0.1.2, which includes the license.
I don't want to deal with publishing it to Open VSX myself. If there's a bot that can do it for me, it has my permission to do so.
