### ISSUE TITLE
Add a reference to the extension "PasteURL"

### ISSUE THREAD

**Issue by iaeiou** [Skn0tt/markdown-link-expander#8]
Hi there,

thanks for your awesome extension!

I'm using it together with this extension: https://github.com/kukushi/PasteURL

As they are complementary, maybe you want to add a reference in your Readme?

(I suggested the same [there](https://github.com/kukushi/PasteURL/issues/15))

**Comment by Skn0tt** [comment]
Awesome to hear you like this extension! Added PasteURL to the Readme, definitely another nice way to go at this problem.
